Fix rocm path detection in `get_rocm_path`
ROCm/numba-hip pull request #4
Opened 2024-12-10 03:37 UTC by braxtoncuneo

Currently, get_rocm_path raises an error if no installation exists at `/opt/rocm/`, even if `ROCM_HOME` or `ROCM_PATH` is set.

I'm in a situation where I cannot add an install at that path, so a fix like this would be lovely.

2024-12-10 11:11 UTC, domcharrier requested changes
Thanks for your contribution! IMO only the change in line 123 is required. Let me know what you think!

2024-12-10 11:11 UTC, domcharrier commented on numba/hip/hipconfig.py
> +        rocm_path = "/opt/rocm/"
IMO only your change in line 123 is required. 

Your other changes would prevent that the `os.path.exists` check is performed for `rocm_path` set via the environment variables `ROCM_PATH` / `ROCM_HOME` .

If we only keep the change in line 123, the code would look as shown below.

```py3
rocm_path = os.environ.get("ROCM_HOME", os.environ.get("ROCM_PATH"))
if rocm_path is None:
    _log.info(
        "neither 'ROCM_PATH' nor 'ROCM_HOME' environment variable specified, trying default path '/opt/rocm'"
    )
    rocm_path = "/opt/rocm/"
if not os.path.exists(rocm_path):
  msg = "no ROCm installation found, checked 'ROCM_PATH' and 'ROCM_HOME' and tried '/opt/rocm'"
  _log.error(msg)
  raise FileNotFoundError(msg)
```

2024-12-10 22:15 UTC, braxtoncuneo commented on numba/hip/hipconfig.py
> +        rocm_path = "/opt/rocm/"
Ah, right :facepalm:. Good catch.

Looks good to me, but I haven't been able to test it myself yet. The AMD system I have access to has quirks that make it a bit more challenging to set up new installs of `numba-hip`.

2024-12-11 18:49 UTC, domcharrier commented
@braxtoncuneo I will merge your PR as soon as the discussed change is implemented.

2024-12-19 23:15 UTC, braxtoncuneo commented
Apologies for the delay. Updated the patch.

2024-12-20 09:16 UTC, merged